#!/bin/bash
alias clearlog='cd ~/projects/solrcloud; pssh -l dporte7 -h pssh_traffic_node_file "echo ''>/var/solr/logs/solr_slow_requests.log"'
alias wipetraffic='cd ~/projects/solrcloud;pssh -l dporte7 -h pssh_traffic_node_file "echo ''>traffic_gen/traffic_gen.log"'
alias viewtraffic='cd ~/projects/solrcloud;pssh -l dporte7 -h pssh_traffic_node_file -P "tail -n 2000 traffic_gen/traffic_gen.log"'
alias search='cd ~/projects/solrcloud;pssh -l dporte7 -h pssh_traffic_node_file -P "cat /var/solr/logs/solr_slow_requests.log"'
alias test='cd ~/projects/solrcloud/tests_v1; bash runtest.sh traffic_gen words.txt --user dporte7'
alias play='cd ~/projects/solrcloud; ansible-playbook -i inventory'
alias closedloop='cd ~/projects/solrcloud/tests_v1; bash runtest.sh traffic_gen words.txt -t 1 -p 1 -c 1 -d 20 --query solrj --loop closed --user dporte7'
alias testlocal='cd ~/projects/solrcloud/tests_v1; bash runtest.sh traffic_gen words.txt --user dporte7'
alias runit='test -t 2 -p 32 -c 1 -d 20 --query direct --loop open'
