# playbook for cloudconfig


- hosts: singleNode
  tasks:
    - name: include the vars
      include_vars: /Users/dporter/projects/solrcloud/playbooks/roles/upload_data/defaults/main.yml

    - name: check if aws has the index
    # aws s3 ls s3://solr-8-dporter/10.10.1.12/reviews_rf32_s1_clustersize12
      shell: aws s3 ls "s3://{{s3_bucket_name}}/{{ansible_subnet}}/{{collection_name}}"
      register: index_result
      ignore_errors: yes

    - name: include aws_pull task when index exists in AWS
      include_tasks:
        file: roles/upload_data/tasks/aws_pull_single.yml
        apply:
          tags:
            - aws_pull
      when: "'PRE' in index_result.stdout"

  tags:
    - never
    - begin_exp



- hosts: singleNode
  tasks:
    - name: this task will run when aws_index is false
      include_tasks: roles/upload_data/tasks/aws_absent.yml
  tags:
    - never
    - begin_exp

# need to put begin_exp tag here to enable tracing.
#  not sure why this is here since this is in solr role.
# - hosts: singleNode
#   tasks:
#     - name: update solr.xml
#       copy:
#         src: /Users/dporter/projects/solrcloud/playbooks/roles/upload_data/files/solr.xml
#         dest: /users/dporte7/solr-8_3/solr/server/solr/
#         force: yes
#   tags:
#     - begin_exp

- hosts: singleNode
  tasks:
    - name: run this at the end of each experiment AKA aws_exp_reset
      include_tasks:
        file: roles/upload_data/tasks/aws_reset_single.yml
  tags:
    - never
    - aws_exp_reset

- hosts: singleNode
  tasks:
    - name: update collection configs
      include_tasks:
        file: roles/upload_data/tasks/all_config.yml
  tags:
    - never
    - update_collection_configs
